### ISSUE TITLE
Videos won't play on iPad after latest iOS update

### ISSUE THREAD

**Issue by AnLand** [zooniverse/chimpandsee#134]
Hi! Videos don't play anymore on iPads after the latest iOS update (10.0.2). I tried with Safari (makes always some problems) and Chrome (usually fine). Nothing works. Volunteers reported that here: https://talk.chimpandsee.org/#/boards/BCP0000008/discussions/DCP0001ex8 Could you please look into this? Thank you!

**Comment by srallen** [comment]
We'll take a look at this as soon as we can, but it likely won't be until next week sometime.

**Comment by astopy** [comment]
This is probably because the videos (and images) are loading over http rather than https. We can't easily update the image locations in the database, so I'd suggest just doing a search and replace on the URLs in the front end somewhere. We did something [similar](https://github.com/zooniverse/Planet-Hunters-2/commit/b77fc6fe2186d08b213904d3926dd91dbe722575) in Planet Hunters.

**Comment by srallen** [comment]
I'm not sure if that is the issue. It looks like the videos are loading over https, but not the preview images. I've tried string replace modeled after Planet Hunters to fix the previews since the video uses the first preview as its poster and the video still isn't playable on iOS safari. I'll push up a separate PR to fix the preview locations since that should be done anyway.

**Comment by srallen** [comment]
One clue: I'm not seeing a network response for the request for the video on the site nor if I try to request the source url directly.
![screen shot 2016-10-12 at 3 00 32 pm](https://cloud.githubusercontent.com/assets/5016731/19325702/f4a41524-908c-11e6-8a71-724dc2423c6e.png)

**Comment by astopy** [comment]
Hmm... that's supposed to redirect to static.zooniverse.org. I wonder if it's not following the redirect.

**Comment by srallen** [comment]
@astopy are there logs on AWS that we can take a look at to determine if the redirect is indeed failing?

**Comment by astopy** [comment]
Logging isn't turned on for most front end requests... I've turned it on for chimpandsee.org now though.

The logs aren't delivered in real time (it takes a few hours), so I'll check back later in the week to see if there's anything in there.

**Comment by astopy** [comment]
I've been debugging this some more this afternoon, and it looks like this is actually a bug in iOS 10. I can't even play the videos in iOS 10 if I upload them to iCloud Drive (but they work in iOS 9), so I'm certain this is nothing to do with HTTPS or anything we're doing on the front end.

It sounds like we're not the only ones, so hopefully Apple will fix this soon:

https://forums.developer.apple.com/thread/51343
https://discussions.apple.com/thread/7682614?start=0&tstart=0

**Comment by AnLand** [comment]
Thanks for letting us know! I wrote an update for our volunteers on Talk. Let's hope that the general problem will be solved soon.
