### ISSUE TITLE
Remove download button on classification videos

### ISSUE THREAD

**Issue by ksigler** [zooniverse/chimpandsee#144]
Videos in classification now have a "download" button on the player toolbar that we would prefer not be available to volunteers.  Is it possible to revert back to how it was, or hide this new button somehow?

It only seems to appear in Chrome (not IE or Firefox) and only on the classification video player, not on the individual subject videos.  If it helps, I'm using Chrome Version 55.0.2883.87 m on a Windows PC.  A screenshot of the new button is below.  It's on the far right.

![Chrome](https://ecwdnq-bn1305.files.1drv.com/y3mRd1XsvqwiqFWYbLtuMDrLdgRETV98jJz6CSOu0DPJmCAPJt5tkwqLSMVkAFnHcsLidcBSmCwigPA_rRp2D4rAD_eY811UT70hgWCprjaDDdt49R7BGZQEzgvPVVqrwX2G4kBsD0KNEk5WNrpiVwGApCnq9TPVnIiVQOJFC4UGsk/Chrome.jpg?psid=1)

Thanks!

**Comment by srallen** [comment]
@ksigler The update to Chrome version 55 added this button to the native video controls UI. I can use some hacky CSS to essentially hide it from view, but this causes an unintended side effect in Safari where its full screen button is pushed off to the side: 

<img width="267" alt="screen shot 2017-01-16 at 10 02 22 am" src="https://cloud.githubusercontent.com/assets/5016731/21991130/01e7af8a-dbd7-11e6-8d45-f0fdde6dd2f9.png">

This button doesn't really add new functionality. Users could always download the videos using the right click context menu. This change just makes it a bit more obvious. Hiding it with CSS should only be seen as a temporary action since the pseudo-classes I can target may change or become unavailable in the future. I'd suggest the science team discuss what they want to do and reply to let me know if they want me to hide it (and if the odd display in Safari is ok). 

As an aside, with the update in version 55, lots of users and developers have complained, so Google is discussing having a way to actual disable the download feature, but there are no guarantees it'll change: https://bugs.chromium.org/p/chromium/issues/detail?id=650174

**Comment by ksigler** [comment]
Thanks, @srallen !  That's very helpful to know that there is a discussion about removing it.  I'm a slow upgrader for this very reason!  I'll make sure the science team gets this information so they can decide what to do.  Do you happen to have any analytics on what devices/browsers most people are using (this would answer a few of our recurring questions)?

**Comment by srallen** [comment]
Here are the ton ten for browser, OS, and device on google analytics:

![pasted image at 2017_01_16 05_12 pm](https://cloud.githubusercontent.com/assets/5016731/21992805/8714dd26-dbdd-11e6-9b5e-3ed81a42f74b.png)
![pasted image at 2017_01_16 05_14 pm](https://cloud.githubusercontent.com/assets/5016731/21992810/89d6ed1a-dbdd-11e6-9d73-18510a1fcc3a.png)
![pasted image at 2017_01_16 05_14 pm 1](https://cloud.githubusercontent.com/assets/5016731/21992812/8bc500e4-dbdd-11e6-9222-675d2836c61c.png)

**Comment by ksigler** [comment]
Spoke with Mimi and she's on board with hiding the download button as a temporary fix.  If Google presents a better solution, or it turns out that it causes any other significant issues, then we should revert.  Does that work for you guys?

**Comment by srallen** [comment]
I've deployed the CSS hack, so the button is now hidden. I've starred that open issue with Google, so I should get emailed whenever there is an update. Hopefully Google prioritizes the issue.

**Comment by ksigler** [comment]
Wonderful, thank you for helping us with this!

**Comment by srallen** [comment]
Noting here that Google added support to disable the download button for HTML5 video and audio in version 58: https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist

We should update to use this instead of the hacky workaround I put in place once we see most of C&S chrome users move to version 58.
